"use client";
import { FormEvent, useState } from "react";

type Data={periodDays:number;visitors:number;starts:number;saves:number;shares:number;pageViews:number;startRate:number;saveRate:number;shareRate:number;daily:{date:string;visitors:number;starts:number;saves:number;shares:number}[]};
export default function AnalyticsAdminPage(){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 async function unlock(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const fd=new FormData(e.currentTarget);try{const res=await fetch("/api/admin/analytics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:String(fd.get("password")||"")})});if(!res.ok)throw new Error();setData(await res.json())}catch{setError("Access denied or dashboard is not configured yet.")}finally{setLoading(false)}}
 if(!data)return <main style={main}><p style={brand}>SENSORY PASSPORT</p><h1>Private Usage Dashboard</h1><p>Anonymous usage numbers only. Passport contents are not included.</p><form onSubmit={unlock} style={form}><label>Admin password<input name="password" type="password" required style={field}/></label><button disabled={loading} style={button}>{loading?"Opening…":"Open Dashboard"}</button>{error&&<p role="alert"><strong>{error}</strong></p>}</form></main>;
 return <main style={{...main,maxWidth:1050}}><p style={brand}>SENSORY PASSPORT</p><h1>Usage Dashboard</h1><p>Last {data.periodDays} days • anonymous sessions</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,margin:"22px 0"}}><Stat l="Visitors" v={data.visitors}/><Stat l="Builder starts" v={data.starts}/><Stat l="Passports saved" v={data.saves}/><Stat l="Share actions" v={data.shares}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:28}}><Stat l="Visitor → start" v={`${Math.round(data.startRate*100)}%`}/><Stat l="Visitor → save" v={`${Math.round(data.saveRate*100)}%`}/><Stat l="Visitor → share" v={`${Math.round(data.shareRate*100)}%`}/></div><h2>Daily activity</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Date","Visitors","Starts","Saves","Shares"].map(x=><th key={x} style={cell}>{x}</th>)}</tr></thead><tbody>{data.daily.map(r=><tr key={r.date}><td style={cell}>{r.date}</td><td style={cell}>{r.visitors}</td><td style={cell}>{r.starts}</td><td style={cell}>{r.saves}</td><td style={cell}>{r.shares}</td></tr>)}</tbody></table></div><p style={{marginTop:24,fontSize:14}}>Privacy: this dashboard does not collect passport names, sensory answers, photos, contacts, or other passport contents.</p></main>
}
function Stat({l,v}:{l:string;v:string|number}){return <div style={{padding:18,border:"1px solid #d7dcda",borderRadius:14}}><div style={{fontSize:13,fontWeight:700}}>{l}</div><div style={{fontSize:30,fontWeight:800,marginTop:4}}>{v}</div></div>}
const main={maxWidth:600,margin:"0 auto",padding:"48px 22px",fontFamily:"Arial,sans-serif",color:"#17211f"};const brand={fontWeight:800,color:"#177f78"};const form={display:"grid",gap:14,marginTop:24,padding:22,border:"1px solid #d7dcda",borderRadius:16};const field={display:"block",width:"100%",marginTop:7,padding:12,borderRadius:9,border:"1px solid #aaa",font:"inherit"};const button={padding:"13px 18px",border:0,borderRadius:10,fontWeight:800,background:"#177f78",color:"white"};const cell={padding:10,borderBottom:"1px solid #ddd",textAlign:"left" as const};
